### ISSUE TITLE
Error enabling version 2.7.17 with qgis_process

### ISSUE THREAD

**Issue by florisvdh** [crocovert/networks#18]
It appears the update to 2.7.17 causes problems (also in the GUI):

```bash
$ qgis_process plugins enable networks
Enabling plugin: "networks"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/floris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/networks/__init__.py", line 40, in classFactory
    from .networks_provider_plugin import NetworksPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/floris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/networks/networks_provider_plugin.py", line 41, in <module>
    from .networks_provider import NetworksProvider
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/floris/.local/share/QGIS/QGIS3/profiles/default/python/plugins/networks/networks_provider.py", line 86, in <module>
    from .list_dir import dirlist
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'networks.list_dir'

error starting plugin: networks

$ 
$ qgis_process --version
QGIS 3.36.3-Maidenhead 'Maidenhead' (2df9655469b)
QGIS code revision 2df9655469b
Qt version 5.15.3
Python version 3.10.12
GDAL/OGR version 3.8.4
PROJ version 9.3.1
EPSG Registry database version v10.098 (2023-11-24)
GEOS version 3.12.1-CAPI-1.18.1
SQLite version 3.37.2
OS Linux Mint 21.3
```

**Comment by crocovert** [comment]
I've uploaded a new version 2.7.19. I hope it will fix it

**Comment by florisvdh** [comment]
It can be loaded again without errors! Thanks @crocovert.
