### ISSUE TITLE
ModuleNotFoundError: No module named 'networks.list_dir'

### ISSUE THREAD

**Issue by paolomartinis** [crocovert/networks#19]
Couldn't load plugin 'networks' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'networks.list_dir' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/paolo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks\__init__.py", line 40, in classFactory
    from .networks_provider_plugin import NetworksPlugin
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/paolo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks\networks_provider_plugin.py", line 41, in 
    from .networks_provider import NetworksProvider
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/paolo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks\networks_provider.py", line 86, in 
    from .list_dir import dirlist
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'networks.list_dir'

Python version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.6-Prizren Prizren, 623828f5

**Comment by teleksterling** [comment]
Same error here after upgrading to Networks 2.7.18

QGIS version               3.34.7-Prizren
Python version           3.12.3
GDAL/OGR version     3.9.0
OS version                  Windows 11 Version 2009

**Comment by crocovert** [comment]
I've uploaded the 2.7.19 which fix the bug, but it's still not yet validated, but it will certainly be soon by a moderator
But you can alreday download it manually and install it with install from zip file.
Best regards

**Comment by crocovert** [comment]
The 2.7.19 version is now available. It should fix the error
